insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (1, 0, 'MEMBROS DAS FORÇAS ARMADAS');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (2, 0, 'POLICIAIS MILITARES');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (3, 0, 'BOMBEIROS MILITARES');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (11, 1, 'MEMBROS SUPERIORES E DIRIGENTES DO PODER PÚBLICO');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (12, 1, 'DIRIGENTES DE EMPRESAS E ORGANIZAÇÕES (EXCETO DE INTERESSE PÚBLICO)');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (13, 1, 'DIRETORES E GERENTES EM EMPRESA DE SERVIÇOS DE SAÚDE, DA EDUCAÇÃO, OU DE SERVIÇOS CULTURAIS, SOCIAIS OU PESSOAIS');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (14, 1, 'GERENTES');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (20, 2, 'PESQUISADORES E PROFISSIONAIS POLICIENTÍFICOS');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (21, 2, 'PROFISSIONAIS DAS CIÊNCIAS EXATAS, FÍSICAS E DA ENGENHARIA');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (22, 2, 'PROFISSIONAIS DAS CIÊNCIAS BIOLÓGICAS, DA SAÚDE E AFINS');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (23, 2, 'PROFISSIONAIS DO ENSINO');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (24, 2, 'PROFISSIONAIS DAS CIÊNCIAS JURÍDICAS');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (25, 2, 'PROFISSIONAIS DAS CIÊNCIAS SOCIAIS E HUMANAS');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (26, 2, 'COMUNICADORES, ARTISTAS E RELIGIOSOS');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (27, 2, 'PROFISSIONAIS EM GASTRONOMIA');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (30, 3, 'TÉCNICOS POLIVALENTES');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (31, 3, 'TÉCNICOS DE NÍVEL MÉDIO DAS CIÊNCIAS FÍSICAS, QUÍMICAS, ENGENHARIA E AFINS');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (32, 3, 'TÉCNICOS DE NÍVEL MÉDIO DAS CIÊNCIAS BIOLÓGICAS, BIOQUÍMICAS, DA SAÚDE E AFINS');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (33, 3, 'PROFESSORES LEIGOS E DE NÍVEL MÉDIO');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (34, 3, 'TÉCNICOS DE NÍVEL MÉDIO EM SERVIÇOS DE TRANSPORTES');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (35, 3, 'TÉCNICOS DE NIVEL MÉDIO NAS CIÊNCIAS ADMINISTRATIVAS');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (37, 3, 'TÉCNICOS EM NIVEL MÉDIO DOS SERVIÇOS CULTURAIS, DAS COMUNICAÇÕES E DOS DESPORTOS');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (39, 3, 'OUTROS TÉCNICOS DE NÍVEL MÉDIO');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (41, 4, 'ESCRITURÁRIOS');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (42, 4, 'TRABALHADORES DE ATENDIMENTO AO PÚBLICO');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (51, 5, 'TRABALHADORES DOS SERVIÇOS');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (52, 5, 'VENDEDORES E PRESTADORES DE SERVIÇOS DO COMÉRCIO');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (61, 6, 'PRODUTORES NA EXPLORAÇÃO AGROPECUÁRIA');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (62, 6, 'TRABALHADORES NA EXPLORAÇÃO AGROPECUÁRIA');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (63, 6, 'PESCADORES E EXTRATIVISTAS FLORESTAIS');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (64, 6, 'TRABALHADORES DA MECANIZAÇÃO AGROPECUÁRIA E FLORESTAL');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (71, 7, 'TRABALHADORES DA INDÚSTRIA EXTRATIVA E DA CONSTRUÇÃO CIVIL');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (72, 7, 'TRABALHADORES DA TRANSFORMAÇÃO DE METAIS E DE COMPÓSITOS');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (73, 7, 'TRABALHADORES DA FABRICAÇÃO E INSTALAÇÃO ELETROELETRÔNICA');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (74, 7, 'MONTADORES DE APARELHOS E INSTRUMENTOS DE PRECISÃO E MUSICAIS');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (75, 7, 'JOALHEIROS, VIDREIROS, CERAMISTAS E AFINS');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (76, 7, 'TRABALHADORES NAS INDÚSTRIAS TÊXTIL, DO CURTIMENTO, DO VESTÚARIO E DAS ARTES GRÁFICAS');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (77, 7, 'TRABALHADORES DAS INDÚSTRIAS DE MADEIRA E DO MOBILIÁRIO');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (78, 7, 'TRABALHADORES DE FUNÇÕES TRANSVERSAIS');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (79, 7, 'TRABALHADORES DO ARTESANATO');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (81, 8, 'TRABALHADORES EM INDÚSTRIAS DE PROCESSOS CONTÍNUOS E OUTRAS INDÚSTRIAS');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (82, 8, 'TRABALHADORES DE INSTALAÇÕES SIDERÚRGICAS E DE MATERIAIS DE CONSTRUÇÃO');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (83, 8, 'TRABALHADORES DE INSTALAÇÕES E MÁQUINAS DE FABRICAÇÃO DE CELULOSE E PAPEL');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (84, 8, 'TRABALHADORES DA FABRICAÇÃO DE ALIMENTOS, BEBIDAS E FUMO');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (86, 8, 'OPERADORES DE PRODUÇÃO, CAPTAÇÃO, TRATAMENTO E DISTRIBUIÇÃO (ENERGIA, ÁGUA E UTILIDADES)');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (87, 8, 'OPERADORES DE OUTRAS INSTALAÇÕES INDUSTRIAIS');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (91, 9, 'TRABALHADORES EM SERVIÇOS DE REPARAÇÃO E MANUTENÇÃO MECÂNICA');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (95, 9, 'POLIMANTENEDORES');
insert into Cbo2002.SubGrupoPrincipal (Codigo, GrandeGrupoCodigo, Titulo) values (99, 9, 'OUTROS TRABALHADORES DA CONSERVAÇÃO, MANUTENÇÃO E REPARAÇÃO');
