insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (10, 01, 'MEMBROS DAS FORÇAS ARMADAS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (20, 02, 'OFICIAIS DE POLÍCIA MILITAR');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (21, 02, 'PRAÇAS DE POLÍCIA MILITAR');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (30, 03, 'OFICIAIS DE BOMBEIRO MILITAR');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (31, 03, 'PRAÇAS DE BOMBEIRO MILITAR');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (111, 11, 'MEMBROS SUPERIORES DO PODER LEGISLATIVO, EXECUTIVO E JUDICIÁRIO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (113, 11, 'CHEFES DE PEQUENAS POPULAÇÕES');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (114, 11, 'DIRIGENTES E ADMINISTRADORES DE ORGANIZAÇÃO DE INTERESSE PÚBLICO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (121, 12, 'DIRETORES GERAIS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (122, 12, 'DIRETORES DE PRODUÇÃO E OPERAÇÕES');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (123, 12, 'DIRETORES DE ÁREAS DE APOIO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (131, 13, 'DIRETORES E GERENTES EM EMPRESA DE SERVIÇOS DE SAÚDE, DE EDUCAÇÃO, OU DE SERVIÇOS CULTURAIS, SOCIAIS OU PESSOAIS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (141, 14, 'GERENTES DE PRODUÇÃO E OPERAÇÕES');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (142, 14, 'GERENTES DE ÁREAS DE APOIO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (201, 20, 'PROFISSIONAIS DA BIOTECNOLOGIA E METROLOGIA');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (202, 20, 'PROFISSIONAIS DA ELETROMECÂNICA');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (203, 20, 'PESQUISADORES');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (204, 20, 'PROFISSIONAIS DE INVESTIGAÇÃO CRIMINAL');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (211, 21, 'MATEMÁTICOS, ESTATÍSTICOS E AFINS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (212, 21, 'PROFISSIONAIS DA INFORMÁTICA');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (213, 21, 'FÍSICOS, QUÍMICOS E AFINS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (214, 21, 'ENGENHEIROS, ARQUITETOS E AFINS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (215, 21, 'PROFISSIONAIS EM NAVEGAÇÃO AÉREA, MARÍTIMA E FLUVIAL');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (221, 22, 'BIÓLOGOS E AFINS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (222, 22, 'AGRÔNOMOS E AFINS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (223, 22, 'PROFISSIONAIS DA MEDICINA, SAÚDE E AFINS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (224, 22, 'PROFISSIONAIS DA EDUCAÇÃO FÍSICA');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (225, 22, 'PROFISSIONAIS DA MEDICINA');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (226, 22, 'PROFISSIONAIS DE SAÚDE EM PRATICAS INTEGRATIVAS E COMPLEMENTARES');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (231, 23, 'PROFESSORES DE NÍVEL SUPERIOR NA EDUCAÇÃO INFANTIL E NO ENSINO FUNDAMENTAL');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (232, 23, 'PROFESSORES DO ENSINO MÉDIO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (233, 23, 'PROFESSORES E INSTRUTORES DO ENSINO PROFISSIONAL');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (234, 23, 'PROFESSORES DO ENSINO SUPERIOR');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (239, 23, 'OUTROS PROFISSIONAIS DO ENSINO NÃO CLASSIFICADOS ANTERIORMENTE');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (241, 24, 'ADVOGADOS, PROCURADORES, TABELIÃES E AFINS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (242, 24, 'ADVOGADOS DO PODER JUDICIÁRIO E DA SEGURANÇA PÚBLICA');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (251, 25, 'CIENTISTAS SOCIAIS, PSICÓLOGOS E AFINS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (252, 25, 'PROFISSIONAIS DE ORGANIZAÇÃO E ADMINISTRAÇÃO DE EMPRESAS E AFINS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (253, 25, 'PROFISSIONAIS DE RELAÇÕES PÚBLICAS, PUBLICIDADE, MARKETING E COMERCIALIZAÇÃO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (254, 25, 'AUDITORES FISCAIS PÚBLICOS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (261, 26, 'PROFISSIONAIS DA COMUNICAÇÃO E DA INFORMAÇÃO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (262, 26, 'PROFISSIONAIS DE ESPETÁCULOS E DAS ARTES');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (263, 26, 'MEMBROS DE CULTOS RELIGIOSOS E AFINS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (271, 27, 'PROFISSIONAIS EM GASTRONOMIA E SERVIÇOS DE ALIMENTAÇÃO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (300, 30, 'TÉCNICOS MECATRÔNICOS E ELETROMECÂNICOS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (301, 30, 'TÉCNICOS EM LABORATÓRIO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (311, 31, 'TÉCNICO EM CIÊNCIAS FÍSICAS E QUÍMICAS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (312, 31, 'TÉCNICOS EM CONSTRUÇÃO CIVIL, DE EDIFICAÇÕES E OBRAS DE INFRAESTRUTURA');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (313, 31, 'TÉCNICOS EM ELETROELETRÔNICA E FOTÔNICA');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (314, 31, 'TÉCNICOS EM METALMECÂNICA');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (316, 31, 'TÉCNICOS EM MINERALOGIA E GEOLOGIA');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (317, 31, 'TÉCNICOS EM INFORMÁTICA');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (318, 31, 'DESENHISTAS TÉCNICOS E MODELISTAS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (319, 31, 'OUTROS TÉCNICOS DE NÍVEL MÉDIO DAS CIÊNCIAS FÍSICAS, QUÍMICAS, ENGENHARIA E AFINS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (320, 32, 'TÉCNICOS EM BIOLOGIA');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (321, 32, 'TÉCNICOS DA PRODUÇÃO AGROPECUÁRIA');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (322, 32, 'TÉCNICOS DA CIÊNCIA DA SAÚDE HUMANA');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (323, 32, 'TÉCNICOS DA CIÊNCIA DA SAÚDE ANIMAL');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (324, 32, 'TÉCNICOS EM OPERAÇÃO DE EQUIPAMENTOS E INSTRUMENTOS DE DIAGNÓSTICO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (325, 32, 'TÉCNICOS DE BIOQUÍMICA E DA BIOTECNOLOGIA');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (328, 32, 'TÉCNICOS EM NECRÓPSIA E TAXIDERMISTAS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (331, 33, 'PROFESSORES DE NÍVEL MÉDIO NA EDUCAÇÃO INFANTIL, NO ENSINO FUNDAMENTAL E NO PROFISSIONALIZANTE');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (332, 33, 'PROFESSORES LEIGOS NO ENSINO FUNDAMENTAL E NO PROFISSIONALIZANTE');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (333, 33, 'INSTRUTORES E PROFESSORES DE ESCOLAS LIVRES');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (334, 33, 'INSPETORES DE ALUNOS E AFINS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (341, 34, 'TÉCNICOS EM NAVEGAÇÃO AÉREA, MARÍTIMA E FLUVIAL');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (342, 34, 'TÉCNICOS EM TRANSPORTES (LOGÍSTICA)');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (351, 35, 'TÉCNICOS DAS CIÊNCIAS ADMINISTRATIVAS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (352, 35, 'TÉCNICOS DE INSPEÇÃO, FISCALIZAÇÃO E COORDENAÇÃO ADMINISTRATIVA');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (353, 35, 'TÉCNICOS DE NÍVEL MÉDIO EM OPERAÇÕES FINANCEIRAS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (354, 35, 'TÉCNICOS DE NIVEL MÉDIO EM OPERAÇÕES COMERCIAIS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (371, 37, 'TÉCNICOS DE SERVIÇOS CULTURAIS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (372, 37, 'TÉCNICOS EM OPERAÇÃO DE CÂMARA FOTOGRÁFICA , CINEMA E DE TELEVISÃO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (373, 37, 'TÉCNICOS EM OPERAÇÃO DE EMISSORAS DE RÁDIO, SISTEMAS DE TELEVISÃO E DE PRODUTORAS DE VÍDEO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (374, 37, 'TÉCNICOS EM OPERAÇÃO DE APARELHOS DE SONORIZAÇÃO, CENOGRAFIA E PROJEÇÃO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (375, 37, 'DECORADORES E VITRINISTAS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (376, 37, 'ARTISTAS DE ARTES POPULARES E MODELOS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (377, 37, 'ATLETAS, DESPORTISTAS E AFINS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (391, 39, 'TÉCNICOS DE NIVEL MÉDIO EM OPERAÇÕES INDUSTRIAIS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (395, 39, 'TÉCNICOS DE APOIO EM PESQUISA E DESENVOLVIMENTO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (410, 41, 'SUPERVISORES DE SERVIÇOS ADMINISTRATIVOS (Exceto de atendimento ao público)');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (411, 41, 'ESCRITURÁRIOS EM GERAL, AGENTES, ASSISTENTES E AUXILIARES ADMINISTRATIVOS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (412, 41, 'SECRETÁRIOS DE EXPEDIENTE E OPERADORES DE MÁQUINAS DE ESCRITÓRIOS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (413, 41, 'ESCRITURÁRIOS CONTÁBEIS E DE FINANÇAS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (414, 41, 'ESCRITURÁRIOS DE CONTROLE DE MATERIAIS E DE APOIO À PRODUÇÃO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (415, 41, 'AUXILIARES DE SERVIÇOS DE BIBLIOTECA, DOCUMENTAÇÃO E CORREIOS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (420, 42, 'SUPERVISORES DE ATENDIMENTO AO PÚBLICO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (421, 42, 'CAIXAS, BILHETEIROS E AFINS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (422, 42, 'TRABALHADORES DE INFORMAÇÕES AO PÚBLICO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (423, 42, 'DESPACHANTES');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (424, 42, 'ENTREVISTADORES, RECENSEADORES E AFINS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (510, 51, 'SUPERVISORES DOS SERVIÇOS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (511, 51, 'TRABALHADORES DOS SERVIÇOS DE TRANSPORTE E TURISMO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (512, 51, 'TRABALHADORES DOS SERVIÇOS DOMÉSTICOS EM GERAL');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (513, 51, 'TRABALHADORES DOS SERVIÇOS DE HOTELARIA E ALIMENTAÇÃO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (514, 51, 'TRABALHADORES NOS SERVIÇOS DE ADMINISTRAÇÃO, CONSERVAÇÃO E MANUTENÇÃO DE EDIFÍCIOS E LOGRADOUROS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (515, 51, 'TRABALHADORES DOS SERVIÇOS DE SAÚDE');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (516, 51, 'TRABALHADORES NOS SERVIÇOS DE EMBELEZAMENTO E CUIDADOS PESSOAIS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (517, 51, 'TRABALHADORES NOS SERVIÇOS DE PROTEÇÃO E SEGURANÇA');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (519, 51, 'OUTROS TRABALHADORES DE SERVIÇOS DIVERSOS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (520, 52, 'SUPERVISORES DE VENDAS E DE PRESTAÇÃO DE SERVIÇOS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (521, 52, 'VENDEDORES E DEMONSTRADORES');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (522, 52, 'REPOSITORES E REMARCADORES DO COMÉRCIO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (523, 52, 'INSTALADORES DE PRODUTOS E ACESSÓRIOS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (524, 52, 'VENDEDORES A DOMICÍLIO, AMBULANTES E EM BANCAS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (611, 61, 'PRODUTORES AGROPECUÁRIOS EM GERAL');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (612, 61, 'PRODUTORES AGRÍCOLAS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (613, 61, 'PRODUTORES EM PECUÁRIA');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (620, 62, 'SUPERVISORES NA EXPLORAÇÃO AGROPECUÁRIA');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (621, 62, 'TRABALHADORES NA EXPLORAÇÃO AGROPECUÁRIA EM GERAL');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (622, 62, 'TRABALHADORES AGRÍCOLAS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (623, 62, 'TRABALHADORES NA PECUÁRIA');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (630, 63, 'SUPERVISORES NA EXPLORAÇÃO FLORESTAL E PESCA');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (631, 63, 'PESCADORES E CAÇADORES');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (632, 63, 'EXTRATIVISTAS FLORESTAIS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (641, 64, 'TRABALHADORES DA MECANIZAÇÃO AGROPECUÁRIA');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (642, 64, 'TRABALHADORES DA MECANIZAÇÃO FLORESTAL');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (643, 64, 'TRABALHADORES DA IRRIGAÇÃO E DRENAGEM');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (710, 71, 'SUPERVISORES DA EXTRAÇÃO MINERAL E DA CONSTRUÇÃO CIVIL');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (711, 71, 'TRABALHADORES DA EXTRAÇÃO MINERAL');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (712, 71, 'TRABALHADORES DE BENEFICIAMENTO DE MINÉRIOS E PEDRAS ORNAMENTAIS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (715, 71, 'TRABALHADORES DA CONSTRUÇÃO CIVIL E OBRAS PÚBLICAS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (716, 71, 'TRABALHADORES DE ACABAMENTO DE OBRAS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (717, 71, 'AJUDANTES DE OBRAS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (720, 72, 'SUPERVISORES DA TRANSFORMAÇÃO DE METAIS E DE COMPÓSITOS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (721, 72, 'TRABALHADORES DE USINAGEM DE METAIS E DE COMPÓSITOS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (722, 72, 'TRABALHADORES DE CONFORMAÇÃO DE METAIS E DE COMPÓSITOS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (723, 72, 'TRABALHADORES DE TRATAMENTO TÉRMICO E DE SUPERFÍCIES DE METAIS E DE COMPÓSITOS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (724, 72, 'TRABALHADORES DE MONTAGEM DE TUBULAÇÕES, ESTRUTURAS METÁLICAS E DE COMPÓSITOS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (725, 72, 'MONTADORES DE MÁQUINAS E APARELHOS MECÂNICOS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (730, 73, 'SUPERVISORES DE MONTAGENS E INSTALAÇÕES ELETROELETRÔNICAS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (731, 73, 'MONTADORES E INSTALADORES DE EQUIPAMENTOS ELETROELETRÔNICOS EM GERAL');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (732, 73, 'INSTALADORES E REPARADORES DE LINHAS E CABOS ELÉTRICOS E DE COMUNICAÇÕES');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (740, 74, 'SUPERVISORES DA MECÂNICA DE PRECISÃO E INSTRUMENTOS MUSICAIS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (741, 74, 'MONTADORES E AJUSTADORES DE INSTRUMENTOS DE PRECISÃO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (742, 74, 'MONTADORES E AJUSTADORES DE INSTRUMENTOS MUSICAIS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (750, 75, 'SUPERVISORES DE JOALHERIA, VIDRARIA, CERÂMICA E AFINS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (751, 75, 'JOALHEIROS E OURIVES');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (752, 75, 'VIDREIROS, CERAMISTAS E AFINS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (760, 76, 'SUPERVISORES NAS INDÚSTRIAS TÊXTIL, DO CURTIMENTO, DO VESTUÁRIO E DAS ARTES GRÁFICAS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (761, 76, 'TRABALHADORES DAS INDUSTRIAS TÊXTEIS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (762, 76, 'TRABALHADORES DO TRATAMENTO DE COUROS E PELES');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (763, 76, 'TRABALHADORES DA CONFECÇÃO DE ROUPAS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (764, 76, 'TRABALHADORES DA CONFECÇÃO DE CALÇADOS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (765, 76, 'TRABALHADORES DA CONFECÇÃO DE ARTEFATOS DE TECIDOS E COUROS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (766, 76, 'TRABALHADORES DA PRODUÇÃO GRÁFICA');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (768, 76, 'TRABALHADORES ARTESANAIS DAS ATIVIDADES TÊXTEIS, DO VESTUÁRIO E DAS ARTES GRÁFICAS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (770, 77, 'SUPERVISORES EM INDÚSTRIA DE MADEIRA, MOBILIÁRIO E DA CARPINTARIA VEICULAR');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (771, 77, 'MARCENEIROS E AFINS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (772, 77, 'TRABALHADORES DA PREPARAÇÃO DA MADEIRA');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (773, 77, 'TRABALHADORES DA TRANSFORMAÇÃO DA MADEIRA E DA FABRICAÇÃO DO MOBILIÁRIO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (774, 77, 'TRABALHADORES DE MONTAGEM DE MÓVEIS E ARTEFATOS DE MADEIRA');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (775, 77, 'TRABALHADORES EM ACABAMENTO DE MADEIRA E DE MOBILIÁRIO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (776, 77, 'TRABALHADORES ARTESANAIS DA MADEIRA E DO MOBILIÁRIO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (777, 77, 'TRABALHADORES DA CARPINTARIA VEICULAR');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (780, 78, 'SUPERVISORES DE TRABALHADORES DE EMBALAGEM E ETIQUETAGEM');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (781, 78, 'OPERADORES DE ROBÔS E EQUIPAMENTOS ESPECIAIS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (782, 78, 'CONDUTORES DE VEÍCULOS E OPERADORES DE EQUIPAMENTOS DE ELEVAÇÃO E DE MOVIMENTAÇÃO DE CARGAS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (783, 78, 'TRABALHADORES DE MANOBRAS SOBRE TRILHOS E MOVIMENTAÇÃO E CARGAS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (784, 78, 'EMBALADORES E ALIMENTADORES DE PRODUÇÃO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (791, 79, 'TRABALHADORES DO ARTESANATO URBANO E RURAL');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (810, 81, 'SUPERVISORES DE PRODUÇÃO, EM INDÚSTRIAS QUÍMICAS, PETROQUÍMICAS E AFINS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (811, 81, 'OPERADORES DE INSTALAÇÕES EM INDÚSTRIAS QUÍMICAS, PETROQUÍMICAS E AFINS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (812, 81, 'TRABALHADORES DA FABRICAÇÃO DE MUNIÇÃO E EXPLOSIVOS QUÍMICOS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (813, 81, 'OPERADORES DE OUTRAS INSTALAÇÕES QUÍMICAS, PETROQUÍMICAS E AFINS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (818, 81, 'OPERADORES DE OPERAÇÃO UNITÁRIA DE LABORATÓRIO (TRANSVERSAL PARA TODA INDÚSTRIA DE PROCESSOS)');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (820, 82, 'SUPERVISORES DE PRODUÇÃO EM INDÚSTRIAS SIDERÚRGICAS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (821, 82, 'OPERADORES DE INSTALAÇÕES E EQUIPAMENTOS DE PRODUÇÃO DE METAIS E LIGAS- PRIMEIRA FUSÃO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (822, 82, 'OPERADORES DE INSTALAÇÕES E EQUIPAMENTOS DE PRODUÇÃO DE METAIS E LIGAS- SEGUNDA FUSÃO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (823, 82, 'TRABALHADORES DE INSTALAÇÕES E EQUIPAMENTOS DE MATERIAL DE CONSTRUÇÃO, CERÂMICA E VIDRO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (828, 82, 'TRABALHADORES ARTESANAIS DA SIDERURGIA E DE MATERIAIS DE CONSTRUÇÃO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (830, 83, 'SUPERVISORES DA FABRICAÇÃO DE CELULOSE E PAPEL');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (831, 83, 'TRABALHADORES DA PREPARAÇÃO DE PASTA DE PAPEL');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (832, 83, 'TRABALHADORES DA FABRICAÇÃO DE PAPEL');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (833, 83, 'CONFECCIONADORES DE PRODUTOS DE PAPEL E PAPELÃO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (840, 84, 'SUPERVISORES DA FABRICAÇÃO DE ALIMENTOS, BEBIDAS E FUMO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (841, 84, 'OPERADORES DE EQUIPAMENTOS NA PREPARAÇÃO DE ALIMENTOS E BEBIDAS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (842, 84, 'OPERADORES NA PREPARAÇÃO DE FUMO E NA FABRICAÇÃO DE CHARUTOS E CIGARROS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (848, 84, 'TRABALHADORES ARTESANAIS NA AGROINDÚSTRIA, NA INDÚSTRIA DE ALIMENTOS E DO FUMO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (860, 86, 'SUPERVISORES DA PRODUÇÃO DE UTILIDADES');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (861, 86, 'OPERADORES NA GERAÇÃO E DISTRIBUIÇÃO DE ENERGIA (CENTRAIS HIDRELÉTRICAS, TERMELÉTRICAS E NUCLEARES)');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (862, 86, 'OPERADORES DE UTILIDADES');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (871, 87, 'OPERADORES DE OUTRAS INSTALAÇÕES INDUSTRIAIS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (910, 91, 'SUPERVISORES EM SERVIÇOS DE REPARAÇÃO E MANUTENÇÃO MECÂNICA');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (911, 91, 'MECÂNICOS DE MANUTENÇÃO DE MÁQUINAS E EQUIPAMENTOS INDUSTRIAIS, COMERCIAIS E RESIDENCIAIS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (913, 91, 'MECÂNICOS DE MANUTENÇÃO DE MÁQUINAS PESADAS E EQUIPAMENTOS AGRÍCOLAS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (914, 91, 'MECÂNICOS DE MANUTENÇÃO VEICULAR');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (915, 91, 'REPARADORES DE INSTRUMENTOS E EQUIPAMENTOS DE PRECISÃO');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (919, 91, 'OUTROS TRABALHADORES NA REPARAÇÃO E MANUTENÇÃO DE EQUIPAMENTOS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (950, 95, 'SUPERVISORES DE MANUTENÇÃO ELETROELETRÔNICA E ELETROMECÂNICA');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (951, 95, 'ELETRICISTAS ELETRÔNICOS DE MANUTENÇÃO INDUSTRIAL, COMERCIAL E RESIDENCIAL');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (953, 95, 'ELETRICISTAS ELETRÔNICOS DE MANUTENÇÃO VEICULAR');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (954, 95, 'MANTENEDORES ELETROMECÂNICOS');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (991, 99, 'OUTROS TRABALHADORES DA CONSERVAÇÃO E MANUTENÇÃO (EXCETO TRABALHADORES ELEMENTARES)');
insert into Cbo2002.SubGrupo (Codigo, SubGrupoPrincipalCodigo, Titulo) values (992, 99, 'TRABALHADORES ELEMENTARES DA MANUTENÇÃO');
