insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (101, 010, 'Oficiais generais das forças armadas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (102, 010, 'Oficiais das forças armadas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (103, 010, 'Praças das forças armadas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (201, 020, 'Oficiais superiores da polícia militar');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (202, 020, 'Capitães da polícia militar');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (203, 020, 'Tenentes da polícia militar');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (211, 021, 'Subtenentes e sargentos da policia militar');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (212, 021, 'Cabos e soldados da polícia militar');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (301, 030, 'Oficiais superiores do corpo de bombeiros militar');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (302, 030, 'Oficiais intermediários do corpo de bombeiros militar');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (303, 030, 'Tenentes do corpo de bombeiros militar');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (311, 031, 'Subtenentes e sargentos do corpo de bombeiros militar');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (312, 031, 'Cabos e soldados do corpo de bombeiros militar');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1111, 111, 'Legisladores');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1112, 111, 'Dirigentes gerais da administração pública');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1113, 111, 'Magistrados');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1114, 111, 'Dirigentes do serviço público');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1115, 111, 'Gestores públicos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1130, 113, 'Dirigentes de povos indígenas, de quilombolas e caiçaras');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1141, 114, 'Dirigentes de partidos políticos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1142, 114, 'Dirigentes e administradores de entidades patronais e dos trabalhadores e de outros interesses sócioeconômicos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1143, 114, 'Dirigentes e administradores de entidades religiosas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1144, 114, 'Dirigentes e administradores de organizações da sociedade civil sem fins lucrativos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1210, 121, 'Diretores gerais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1221, 122, 'Diretores de produção e operações em empresa agropecuária, pesqueira , aqüícola e florestal');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1222, 122, 'Diretores de produção e operações em empresa da indústria extrativa, transformação e de serviços de utilidade pública');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1223, 122, 'Diretores de operações de obras em empresa de construção');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1224, 122, 'Diretores de operações em empresa do comércio');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1225, 122, 'Diretores de serviços de turismo, de alojamento e de alimentação');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1226, 122, 'Diretores de operações de serviços em empresa de armazenamento, de transporte e de telecomunicação');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1227, 122, 'Diretores de operações de serviços em instituição de intermediação financeira');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1231, 123, 'Diretores administrativos e financeiros');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1232, 123, 'Diretores de recursos humanos e relações de trabalho');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1233, 123, 'Diretores de comercialização e marketing');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1234, 123, 'Diretores de suprimentos e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1236, 123, 'Diretores de tecnologia da informação');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1237, 123, 'Diretores de pesquisa e desenvolvimento');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1238, 123, 'Diretores de manutenção');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1311, 131, 'Diretores e gerentes de operações em empresa de serviços pessoais, sociais e culturais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1312, 131, 'Gestores e especialistas de operações em empresas, secretarias e unidades de serviços de saúde');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1313, 131, 'Diretores e gerentes de instituição de serviços educacionais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1411, 141, 'Gerentes de produção e operações em empresa agropecuária, pesqueira, aqüícola e florestal');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1412, 141, 'Gerentes de produção e operações em empresa da indústria extrativa, de transformação e de serviços de utilidade pública');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1413, 141, 'Gerentes de obras em empresa de construção');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1414, 141, 'Gerentes de operações comerciais e de assistência técnica');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1415, 141, 'Gerentes de operações de serviços em empresa de turismo, de alojamento e alimentação');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1416, 141, 'Gerentes de operações de serviços em empresa de transporte, de comunicação e de logística (armazenagem e distribuição)');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1417, 141, 'Gerentes de operações de serviços em instituição de intermediação financeira');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1418, 141, 'Gerentes operacionais da aviação civil');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1421, 142, 'Gerentes administrativos, financeiros, de riscos e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1422, 142, 'Gerentes de recursos humanos e de relações do trabalho');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1423, 142, 'Gerentes de comercialização, marketing e comunicação');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1424, 142, 'Gerentes de suprimentos e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1425, 142, 'Gerentes de tecnologia da informação');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1426, 142, 'Gerentes de pesquisa e desenvolvimento e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (1427, 142, 'Gerentes de manutenção e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2011, 201, 'Profissionais da biotecnologia');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2012, 201, 'Profissionais da metrologia');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2021, 202, 'Engenheiros de controle e automação, engenheiros mecatrônicos e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2030, 203, 'Pesquisadores das ciências biológicas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2031, 203, 'Pesquisadores das ciências naturais e exatas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2032, 203, 'Pesquisadores de engenharia e tecnologia');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2033, 203, 'Pesquisadores das ciências da saúde');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2034, 203, 'Pesquisadores das ciências da agricultura');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2035, 203, 'Pesquisadores das ciências sociais e humanas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2041, 204, 'Peritos criminais e judiciais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2111, 211, 'Profissionais da matemática');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2112, 211, 'Profissionais de estatística');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2122, 212, 'Engenheiros em computação');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2123, 212, 'Administradores de tecnologia da informação');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2124, 212, 'Analistas de tecnologia da informação');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2131, 213, 'Físicos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2132, 213, 'Químicos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2133, 213, 'Profissionais das ciências atmosféricas e espaciais e de astronomia');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2134, 213, 'Geólogos, oceanógrafos, geofísicos e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2140, 214, 'Engenheiros ambientais e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2141, 214, 'Arquitetos e urbanistas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2142, 214, 'Engenheiros civis e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2143, 214, 'Engenheiros eletricistas, eletrônicos e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2144, 214, 'Engenheiros mecânicos e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2145, 214, 'Engenheiros químicos e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2146, 214, 'Engenheiros metalurgistas, de materiais e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2147, 214, 'Engenheiros de minas e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2148, 214, 'Engenheiros agrimensores e engenheiros cartógrafos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2149, 214, 'Engenheiros de produção, qualidade, segurança e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2151, 215, 'Oficiais de convés e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2152, 215, 'Oficiais de máquinas da marinha mercante');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2153, 215, 'Profissionais da pilotagem aeronáutica');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2211, 221, 'Biólogos e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2212, 221, 'Biomédicos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2221, 222, 'Engenheiros agrossilvipecuários');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2222, 222, 'Engenheiros de alimentos e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2232, 223, 'Cirurgiões-dentistas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2233, 223, 'Veterinários e zootecnistas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2234, 223, 'Farmacêuticos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2235, 223, 'Enfermeiros e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2236, 223, 'Fisioterapeutas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2237, 223, 'Nutricionistas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2238, 223, 'Fonoaudiólogos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2239, 223, 'Terapeutas ocupacionais, ortoptistas e psicomotricistas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2241, 224, 'Profissionais da educação física');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2251, 225, 'Médicos clínicos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2252, 225, 'Médicos em especialidades cirúrgicas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2253, 225, 'Médicos em medicina diagnóstica e terapêutica');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2261, 226, 'Osteopatas e quiropraxistas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2263, 226, 'Profissionais das terapias criativas,equoterápicas e naturológicas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2311, 231, 'Professores de nível superior na educação infantil');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2312, 231, 'Professores de nível superior do ensino fundamental (primeira a quarta séries)');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2313, 231, 'Professores de nível superior no ensino fundamental de quinta a oitava série');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2321, 232, 'Professores do ensino médio');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2331, 233, 'Professores do ensino profissional');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2332, 233, 'Instrutores de ensino profissional');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2341, 234, 'Professores de matemática, estatística e informática do ensino superior');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2342, 234, 'Professores de ciências físicas, químicas e afins do ensino superior');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2343, 234, 'Professores de arquitetura e urbanismo, engenharia, geofísica e geologia do ensino superior');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2344, 234, 'Professores de ciências biológicas e da saúde do ensino superior');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2345, 234, 'Professores na área de formação pedagógica do ensino superior');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2346, 234, 'Professores nas áreas de língua e literatura do ensino superior');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2347, 234, 'Professores de ciências humanas do ensino superior');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2348, 234, 'Professores de ciências econômicas, administrativas e contábeis do ensino superior');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2349, 234, 'Professores de artes do ensino superior');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2392, 239, 'Professores de educação especial');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2394, 239, 'Programadores, avaliadores e orientadores de ensino');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2410, 241, 'Advogados');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2412, 241, 'Procuradores e advogados públicos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2413, 241, 'Tabeliães e registradores');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2414, 241, 'Conselheiros julgadores');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2422, 242, 'Membros do ministério público');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2423, 242, 'Delegados de polícia');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2424, 242, 'Defensores públicos e procuradores da assistência judiciária');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2429, 242, 'Profissionais da inteligência');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2511, 251, 'Profissionais em pesquisa e análise antropológica sociológica');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2512, 251, 'Economistas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2513, 251, 'Profissionais em pesquisa e análise geográfica');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2514, 251, 'Filósofos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2515, 251, 'Psicólogos e psicanalistas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2516, 251, 'Assistentes sociais e economistas domésticos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2521, 252, 'Administradores');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2522, 252, 'Contadores e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2523, 252, 'Secretárias(os) executivas(os) e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2524, 252, 'Profissionais de recursos humanos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2525, 252, 'Profissionais de administração ecônomico-financeira');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2526, 252, 'Profissionais da administração dos serviços de segurança');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2527, 252, 'Profissionais de planejamento, programação e controles logisticos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2531, 253, 'Profissionais de publicidade');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2532, 253, 'Profissionais de comercializacão e consultoria de serviços bancários');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2533, 253, 'Corretores de valores, ativos financeiros, mercadorias e derivativos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2534, 253, 'Profissionais de mídias digitais e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2541, 254, 'Auditores fiscais e técnicos da receita federal');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2542, 254, 'Auditores fiscais da previdência social');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2543, 254, 'Auditores fiscais do trabalho');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2544, 254, 'Fiscais de tributos estaduais e municipais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2545, 254, 'Profissionais da fiscalização de atividades urbanas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2611, 261, 'Profissionais do jornalismo');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2612, 261, 'Profissionais da informação');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2613, 261, 'Arquivistas e museólogos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2614, 261, 'Filólogos,tradutores ,intérpretes e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2615, 261, 'Profissionais da escrita');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2616, 261, 'Editores');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2617, 261, 'Locutores, comentaristas e repórteres de mídias audiovisuais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2618, 261, 'Fotógrafos profissionais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2619, 261, 'Assistentes de direção (tv) e continuístas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2621, 262, 'Produtores artísticos e culturais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2622, 262, 'Diretores de espetáculos e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2623, 262, 'Cenógrafos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2624, 262, 'Artistas visuais,desenhistas industriais e conservadores-restauradores de bens culturais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2625, 262, 'Atores');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2626, 262, 'Músicos compositores, arranjadores, regentes e musicólogos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2627, 262, 'Músicos intérpretes');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2628, 262, 'Artistas da dança (exceto dança tradicional e popular)');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2629, 262, 'Designer de interiores de nível superior');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2631, 263, 'Ministros de culto, missionários, teólogos e profissionais assemelhados');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (2711, 271, 'Chefes de cozinha e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3001, 300, 'Técnicos em mecatrônica');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3003, 300, 'Técnicos em eletromecânica');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3011, 301, 'Técnicos de laboratório industrial');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3012, 301, 'Técnicos de apoio à bioengenharia');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3111, 311, 'Técnicos químicos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3112, 311, 'Técnicos de produção de indústrias químicas, petroquímicas, refino de petróleo, gás e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3113, 311, 'Técnicos em materiais, produtos cerâmicos e vidros');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3114, 311, 'Técnicos em fabricação de produtos plásticos e de borracha');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3115, 311, 'Técnicos em controle ambiental, utilidades e tratamento de efluentes');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3116, 311, 'Técnicos têxteis');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3117, 311, 'Coloristas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3121, 312, 'Técnicos em construção civil (edificações)');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3122, 312, 'Técnicos em construção civil (obras de infraestrutura)');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3123, 312, 'Técnicos em geomática');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3131, 313, 'Técnicos em eletricidade e eletrotécnica');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3132, 313, 'Técnicos em eletrônica');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3133, 313, 'Técnicos em telecomunicações');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3134, 313, 'Técnicos em calibração e instrumentação');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3135, 313, 'Técnicos em fotônica');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3141, 314, 'Técnicos mecânicos na fabricação e montagem de máquinas, sistemas e instrumentos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3142, 314, 'Técnicos mecânicos (ferramentas)');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3143, 314, 'Técnicos em mecânica veicular');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3144, 314, 'Técnicos mecânicos na manutenção de máquinas, sistemas e instrumentos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3146, 314, 'Técnicos em metalurgia (estruturas metálicas)');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3147, 314, 'Técnicos em siderurgia');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3148, 314, 'Especialistas em inspeções industriais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3161, 316, 'Técnicos em geologia');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3163, 316, 'Técnicos em mineração');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3171, 317, 'Técnicos de desenvolvimento de sistemas e aplicações');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3172, 317, 'Técnicos de suporte e monitoração ao usuário de tecnologia da informação.');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3180, 318, 'Desenhistas técnicos, em geral');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3181, 318, 'Desenhistas técnicos da construção civil e arquitetura');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3182, 318, 'Desenhistas técnicos da mecânica');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3183, 318, 'Desenhistas técnicos em eletricidade, eletrônica, eletromecânica, calefação, ventilação e refrigeração');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3184, 318, 'Desenhistas técnicos de produtos e serviços diversos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3185, 318, 'Desenhistas projetistas de construção civil e arquitetura');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3186, 318, 'Desenhistas projetistas da mecânica');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3187, 318, 'Desenhistas projetistas da eletrônica');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3188, 318, 'Desenhistas projetistas e modelistas de produtos e serviços diversos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3191, 319, 'Técnicos do vestuário');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3192, 319, 'Técnicos do mobiliário e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3201, 320, 'Técnicos em biologia');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3211, 321, 'Técnicos agrícolas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3212, 321, 'Técnicos florestais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3213, 321, 'Técnicos em aqüicultura');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3221, 322, 'Tecnólogos e técnicos em terapias complementares e estéticas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3222, 322, 'Técnicos e auxiliares de enfermagem');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3223, 322, 'Técnicos em óptica e optometria');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3224, 322, 'Técnicos de odontologia');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3225, 322, 'Técnicos em próteses ortopédicas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3226, 322, 'Técnicos de imobilizações ortopédicas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3231, 323, 'Técnicos em pecuária');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3241, 324, 'Tecnólogos e técnicos em métodos de diagnósticos e terapêutica');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3242, 324, 'Técnicos de laboratórios de saúde e bancos de sangue');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3250, 325, 'Enólogos, perfumistas e aromistas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3251, 325, 'Técnico em farmácia e em manipulação farmacêutica');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3252, 325, 'Técnicos em produção, conservação e de qualidade de alimentos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3253, 325, 'Técnicos de apoio à biotecnologia');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3281, 328, 'Técnicos em necrópsia e taxidermistas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3311, 331, 'Professores de nível médio na educação infantil');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3312, 331, 'Professores de nível médio no ensino fundamental');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3313, 331, 'Professores de nível médio no ensino profissionalizante');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3321, 332, 'Professores leigos no ensino fundamental');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3322, 332, 'Professores práticos no ensino profissionalizante');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3331, 333, 'Instrutores e professores de cursos livres');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3341, 334, 'Inspetores de alunos e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3411, 341, 'Pilotos de aviação comercial, mecânicos de vôo e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3412, 341, 'Técnicos marítimos, fluviários e pescadores de convés');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3413, 341, 'Técnicos marítimos e fluviários de máquinas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3421, 342, 'Especialistas em logística de transportes');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3422, 342, 'Despachantes aduaneiros');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3423, 342, 'Técnicos em transportes rodoviários');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3424, 342, 'Técnicos em transportes metroferroviários');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3425, 342, 'Técnicos em transportes aéreos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3426, 342, 'Técnicos em transportes por vias navegáveis e operações portuárias');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3511, 351, 'Técnicos em contabilidade');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3513, 351, 'Técnicos em administração');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3514, 351, 'Serventuários da justiça e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3515, 351, 'Técnicos em secretariado, taquígrafos e estenotipistas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3516, 351, 'Técnicos em segurança do trabalho');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3517, 351, 'Técnicos de seguros e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3518, 351, 'Agentes de investigação e identificação');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3519, 351, 'Técnicos da inteligência');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3522, 352, 'Agentes da saúde e do meio ambiente');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3523, 352, 'Agentes fiscais metrológicos e de qualidade');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3524, 352, 'Profissionais de direitos autorais e de avaliacão de produtos dos meios de comunicação');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3532, 353, 'Técnicos em operações e serviços bancários');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3541, 354, 'Especialistas em promoção de produtos e vendas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3542, 354, 'Compradores');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3543, 354, 'Analistas de comércio exterior');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3544, 354, 'Leiloeiros e avaliadores');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3545, 354, 'Corretores de seguros');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3546, 354, 'Corretores de imóveis e de grãos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3547, 354, 'Representantes comerciais autônomos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3548, 354, 'Técnicos em serviços de turismo e organização de eventos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3711, 371, 'Técnicos em biblioteconomia');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3712, 371, 'Técnicos em museologia e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3713, 371, 'Técnicos em artes gráficas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3714, 371, 'Recreadores');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3721, 372, 'Captadores de imagens em movimento');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3722, 372, 'Operadores de rede de teleprocessamento e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3731, 373, 'Técnicos de operação de registros sonoro/audiovisuais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3732, 373, 'Supervisores operacionais e técnicos em mídias audiovisuais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3741, 374, 'Técnicos em áudio');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3742, 374, 'Técnicos em cenografia');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3743, 374, 'Técnicos em operação de aparelhos de projeção');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3744, 374, 'Técnicos em montagem, edição e finalização de mídia audiovisual');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3751, 375, 'Designers de interiores, de vitrines e visual merchandiser e afins (nível médio)');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3761, 376, 'Dançarinos tradicionais e populares');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3762, 376, 'Artistas de circo (circenses)');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3763, 376, 'Apresentadores de eventos, programas e espetáculos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3764, 376, 'Modelos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3771, 377, 'Atletas profissionais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3772, 377, 'Árbitros desportivos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3911, 391, 'Planejadores, programadores e controladores de produção e manutenção');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3912, 391, 'Técnicos de controle da produção');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (3951, 395, 'Técnicos de apoio em pesquisa e desenvolvimento');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (4101, 410, 'Supervisores administrativos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (4102, 410, 'Supervisores de serviços financeiros, de câmbio e de controle');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (4110, 411, 'Agentes, assistentes e auxiliares administrativos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (4121, 412, 'Operadores de equipamentos de entrada e transmissão de dados');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (4122, 412, 'Contínuos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (4131, 413, 'Auxiliares de contabilidade');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (4132, 413, 'Escriturários de serviços bancários');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (4141, 414, 'Almoxarifes e armazenistas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (4142, 414, 'Apontadores e conferentes');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (4151, 415, 'Auxiliares de serviços de documentação, informação e pesquisa');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (4152, 415, 'Trabalhadores nos serviços de classificação e entregas de correspondências, encomendas e publicações');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (4153, 415, 'Trabalhadores em registros e informações em saúde');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (4201, 420, 'Supervisores de atendimento ao público e de pesquisa');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (4211, 421, 'Caixas e bilheteiros (exceto caixa de banco)');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (4212, 421, 'Coletadores de apostas e de jogos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (4213, 421, 'Cobradores e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (4221, 422, 'Recepcionistas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (4222, 422, 'Operadores de telefonia');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (4223, 422, 'Operadores de telemarketing e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (4231, 423, 'Despachantes documentalistas e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (4241, 424, 'Entrevistadores e recenseadores');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (4242, 424, 'Aplicadores de provas e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5101, 510, 'Supervisores dos serviços de transporte, turismo, hotelaria e administração de edifícios');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5102, 510, 'Supervisores de lavanderia');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5103, 510, 'Supervisores dos serviços de proteção, segurança e outros');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5111, 511, 'Trabalhadores de segurança e atendimento aos usuários nos transportes');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5112, 511, 'Fiscais e cobradores dos transportes coletivos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5114, 511, 'Guias de turismo');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5115, 511, 'Condutores de turismo');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5121, 512, 'Trabalhadores dos serviços domésticos em geral');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5131, 513, 'Mordomos e governantas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5132, 513, 'Cozinheiros');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5133, 513, 'Camareiros, roupeiros e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5134, 513, 'Trabalhadores no atendimento em estabelecimentos de serviços de alimentação, bebidas e hotelaria');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5135, 513, 'Trabalhadores auxiliares nos serviços de alimentação');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5136, 513, 'Churrasqueiros, pizzaiolos e sushimen');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5141, 514, 'Trabalhadores nos serviços de administração de edifícios');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5142, 514, 'Trabalhadores nos serviços de coleta de resíduos, de limpeza e conservação de áreas públicas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5143, 514, 'Trabalhadores nos serviços de manutenção de edificações');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5151, 515, 'Trabalhadores em serviços de promoção e apoio à saúde');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5152, 515, 'Auxiliares de laboratório da saúde');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5153, 515, 'Trabalhadores de atenção, defesa e proteção a pessoas em situação de risco e adolescentes em conflito com a lei');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5161, 516, 'Trabalhadores nos serviços de embelezamento e higiene');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5162, 516, 'Cuidadores de crianças, jovens, adultos e idosos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5163, 516, 'Tintureiros, lavadeiros e afins, a máquina');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5164, 516, 'Lavadores e passadores de roupa, a mão');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5165, 516, 'Trabalhadores dos serviços funerários');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5166, 516, 'Trabalhadores auxiliares dos serviços funerários');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5167, 516, 'Astrólogos e numerólogos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5168, 516, 'Esotéricos e paranormais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5171, 517, 'Bombeiros, salva-vidas e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5172, 517, 'Policiais, guardas-civis municipais e agentes de trânsito');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5173, 517, 'Vigilantes e guardas de segurança');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5174, 517, 'Porteiros, vigias e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5191, 519, 'Motociclistas e ciclistas de entregas rápidas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5192, 519, 'Trabalhadores da coleta e seleção de material reciclável');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5193, 519, 'Trabalhadores de serviços veterinários, de higiene e estética de animais domésticos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5198, 519, 'Profissionais do sexo');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5199, 519, 'Outros trabalhadores dos serviços');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5201, 520, 'Supervisores de vendas e de prestação de serviços');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5211, 521, 'Operadores do comércio em lojas e mercados');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5231, 523, 'Instaladores de produtos e acessórios');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5241, 524, 'Vendedores em domicílio');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5242, 524, 'Vendedores em bancas, quiosques e barracas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (5243, 524, 'Vendedores ambulantes');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6110, 611, 'Produtores agropecuários em geral');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6120, 612, 'Produtores agrícolas polivalentes');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6121, 612, 'Produtores agrícolas na cultura de gramíneas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6122, 612, 'Produtores agrícolas na cultura de plantas fibrosas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6123, 612, 'Produtores agrícolas na olericultura');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6124, 612, 'Produtores agrícolas no cultivo de flores e plantas ornamentais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6125, 612, 'Produtores agrícolas na fruticultura');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6126, 612, 'Produtores agrícolas na cultura de plantas estimulantes');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6127, 612, 'Produtores agrícolas na cultura de plantas oleaginosas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6128, 612, 'Produtores de especiarias e de plantas aromáticas e medicinais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6130, 613, 'Produtores em pecuária polivalente');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6131, 613, 'Produtores em pecuária de animais de grande porte');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6132, 613, 'Produtores em pecuária de animais de médio porte');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6133, 613, 'Produtores da avicultura e cunicultura');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6134, 613, 'Produtores de animais e insetos úteis');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6201, 620, 'Supervisores na exploração agropecuária');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6210, 621, 'Trabalhadores agropecuários em geral');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6220, 622, 'Trabalhadores de apoio à agricultura');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6221, 622, 'Trabalhadores agrícolas na cultura de gramíneas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6222, 622, 'Trabalhadores agrícolas na cultura de plantas fibrosas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6223, 622, 'Trabalhadores agrícolas na olericultura');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6224, 622, 'Trabalhadores agrícolas no cultivo de flores e plantas ornamentais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6225, 622, 'Trabalhadores agrícolas na fruticultura');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6226, 622, 'Trabalhadores agrícolas nas culturas de plantas estimulantes');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6227, 622, 'Trabalhadores agrícolas na cultura de plantas oleaginosas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6228, 622, 'Trabalhadores agrícolas da cultura de especiarias e de plantas aromáticas e medicinais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6230, 623, 'Tratadores polivalentes de animais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6231, 623, 'Trabalhadores na pecuária de animais de grande porte');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6232, 623, 'Trabalhadores na pecuária de animais de médio porte');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6233, 623, 'Trabalhadores na avicultura e cunicultura');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6234, 623, 'Trabalhadores na criação de insetos e animais úteis');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6301, 630, 'Supervisores na área florestal e aqüicultura');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6310, 631, 'Pescadores polivalentes');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6311, 631, 'Pescadores profissionais artesanais de água doce');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6312, 631, 'Pescadores de água costeira e alto mar');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6313, 631, 'Criadores de animais aquáticos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6314, 631, 'Trabalhadores de apoio à pesca');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6320, 632, 'Trabalhadores florestais polivalentes');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6321, 632, 'Extrativistas e reflorestadores de espécies produtoras de madeira');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6322, 632, 'Extrativistas florestais de espécies produtoras de gomas e resinas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6323, 632, 'Extrativistas florestais de espécies produtoras de fibras, ceras e óleos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6324, 632, 'Extrativistas florestais de espécies produtoras de alimentos silvestres');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6325, 632, 'Extrativistas florestais de espécies produtoras de substâncias aromáticas, medicinais e tóxicas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6326, 632, 'Carvoejadores');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6410, 641, 'Trabalhadores da mecanização agrícola');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6420, 642, 'Trabalhadores da mecanização florestal');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (6430, 643, 'Trabalhadores da irrigação e drenagem');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7101, 710, 'Supervisores da extração mineral');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7102, 710, 'Supervisores da construção civil');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7111, 711, 'Trabalhadores da extração de minerais sólidos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7112, 711, 'Trabalhadores de extração de minerais sólidos (operadores de máquinas)');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7113, 711, 'Trabalhadores da extração de minerais líquidos e gasosos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7114, 711, 'Garimpeiros e operadores de salinas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7121, 712, 'Trabalhadores de beneficiamento de minérios');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7122, 712, 'Trabalhadores de beneficiamento de pedras ornamentais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7151, 715, 'Trabalhadores na operação de máquinas de terraplenagem e fundações');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7152, 715, 'Trabalhadores de estruturas de alvenaria');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7153, 715, 'Montadores de estruturas de concreto armado');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7154, 715, 'Trabalhadores na operação de máquinas de concreto usinado e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7155, 715, 'Trabalhadores de montagem de estruturas de madeira, metal e compósitos em obras civis');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7156, 715, 'Trabalhadores de instalações elétricas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7157, 715, 'Aplicadores de materiais isolantes');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7161, 716, 'Revestidores de concreto');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7162, 716, 'Telhadores (revestimentos rígidos)');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7163, 716, 'Vidraceiros (revestimentos rígidos)');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7164, 716, 'Gesseiros');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7165, 716, 'Aplicadores de revestimentos cerâmicos, pastilhas, pedras e madeiras');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7166, 716, 'Pintores de obras e revestidores de interiores (revestimentos flexíveis)');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7170, 717, 'Ajudantes de obras civis');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7201, 720, 'Supervisores de usinagem, conformação e tratamento de metais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7202, 720, 'Supervisores da fabricação e montagem metalmecânica');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7211, 721, 'Ferramenteiros e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7212, 721, 'Preparadores e operadores de máquinas-ferramenta convencionais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7213, 721, 'Afiadores e polidores de metais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7214, 721, 'Operadores de máquinas de usinagem cnc');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7221, 722, 'Trabalhadores de forjamento de metais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7222, 722, 'Trabalhadores de fundição de metais puros e de ligas metálicas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7223, 722, 'Trabalhadores de moldagem de metais e de ligas metálicas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7224, 722, 'Trabalhadores de trefilação e estiramento de metais puros e ligas metálicas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7231, 723, 'Trabalhadores de tratamento térmico de metais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7232, 723, 'Trabalhadores de tratamento de superfícies de metais e de compósitos (termoquímicos)');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7233, 723, 'Trabalhadores da pintura de equipamentos, veículos, estruturas metálicas e de compósitos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7241, 724, 'Encanadores e instaladores de tubulações');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7242, 724, 'Trabalhadores de traçagem e montagem de estruturas metálicas e de compósitos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7243, 724, 'Trabalhadores de soldagem e corte de ligas metálicas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7244, 724, 'Trabalhadores de caldeiraria e serralheria');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7245, 724, 'Operadores de máquinas de conformação de metais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7246, 724, 'Trançadores e laceiros de cabos de aço');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7250, 725, 'Ajustadores mecânicos polivalentes e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7251, 725, 'Montadores de máquinas, aparelhos e acessórios em linhas de montagem');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7252, 725, 'Montadores de máquinas industriais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7253, 725, 'Montadores de máquinas pesadas e equipamentos agrícolas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7254, 725, 'Mecânicos montadores de motores e turboalimentadores');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7255, 725, 'Montadores de veículos automotores (linha de montagem)');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7256, 725, 'Montadores de sistemas e estruturas de aeronaves');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7257, 725, 'Instaladores de equipamentos de refrigeração e ventilação');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7301, 730, 'Supervisores de montagens e instalações eletroeletrônicas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7311, 731, 'Montadores de equipamentos eletroeletrônicos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7312, 731, 'Montadores de aparelhos de telecomunicações');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7313, 731, 'Instaladores-reparadores de linhas e equipamentos de telecomunicações');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7321, 732, 'Instaladores e reparadores de linhas e cabos elétricos, telefônicos e de comunicação de dados');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7401, 740, 'Supervisores da mecânica de precisão e instrumentos musicais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7411, 741, 'Mecânicos de instrumentos de precisão');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7421, 742, 'Confeccionadores de instrumentos musicais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7501, 750, 'Supervisores de joalheria e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7502, 750, 'Supervisores de vidraria, cerâmica e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7510, 751, 'Joalheiros e lapidadores de gemas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7511, 751, 'Artesãos de metais preciosos e semi-preciosos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7521, 752, 'Sopradores, moldadores e modeladores de vidros e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7522, 752, 'Trabalhadores da transformação de vidros planos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7523, 752, 'Ceramistas (preparação e fabricação)');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7524, 752, 'Vidreiros e ceramistas (arte e decoração)');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7601, 760, 'Supervisores da indústria têxtil');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7602, 760, 'Supervisores na indústria do curtimento');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7603, 760, 'Supervisores na confecção do vestuário');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7604, 760, 'Supervisores na confecção de calçados');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7605, 760, 'Supervisores da confecção de artefatos de tecidos, couros e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7606, 760, 'Supervisores das artes gráficas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7610, 761, 'Trabalhadores polivalentes das indústrias têxteis');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7611, 761, 'Trabalhadores da classificação de fibras têxteis e lavagem de lã');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7612, 761, 'Operadores da fiação');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7613, 761, 'Operadores de tear e máquinas similares');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7614, 761, 'Trabalhadores de acabamento, tingimento e estamparia das indústrias têxteis');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7618, 761, 'Inspetores e revisores de produção têxtil');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7620, 762, 'Trabalhadores polivalentes do curtimento de couros e peles');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7621, 762, 'Trabalhadores da preparação do curtimento de couros e peles');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7622, 762, 'Trabalhadores do curtimento de couros e peles');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7623, 762, 'Trabalhadores do acabamento de couros e peles');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7630, 763, 'Profissionais polivalentes da confecção de roupas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7631, 763, 'Trabalhadores da preparação da confecção de roupas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7632, 763, 'Operadores de máquinas para costura de peças do vestuário');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7633, 763, 'Operadores de máquinas para bordado e acabamento de roupas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7640, 764, 'Trabalhadores polivalentes da confecção de calçados');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7641, 764, 'Trabalhadores da preparação da confecção de calçados');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7642, 764, 'Operadores de máquinas de costurar e montar calçados');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7643, 764, 'Trabalhadores de acabamento de calçados');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7650, 765, 'Trabalhadores polivalentes da confecção de artefatos de tecidos e couros');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7651, 765, 'Trabalhadores da preparação de artefatos de tecidos, couros e tapeçaria');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7652, 765, 'Trabalhadores da confecção de artefatos de tecidos, couros e sintéticos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7653, 765, 'Operadores de máquinas na confecção de artefatos de couro');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7654, 765, 'Trabalhadores do acabamento de artefatos de tecidos e couros');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7661, 766, 'Trabalhadores da pré-impressão gráfica');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7662, 766, 'Trabalhadores da impressão gráfica');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7663, 766, 'Trabalhadores do acabamento gráfico');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7664, 766, 'Trabalhadores de laboratório fotográfico e radiológico');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7681, 768, 'Trabalhadores de tecelagem manual, tricô, crochê, rendas e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7682, 768, 'Trabalhadores artesanais da confecção de peças e tecidos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7683, 768, 'Trabalhadores artesanais da confecção de calçados e artefatos de couros e peles');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7686, 768, 'Trabalhadores tipográficos linotipistas e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7687, 768, 'Encadernadores e recuperadores de livros (pequenos lotes ou a unidade)');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7701, 770, 'Supervisores em indústria de madeira, mobiliário e da carpintaria veicular');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7711, 771, 'Marceneiros e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7721, 772, 'Trabalhadores de tratamento e preparação da madeira');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7731, 773, 'Operadores de máquinas de desdobramento da madeira');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7732, 773, 'Operadores de máquinas de aglomeração e prensagem de chapas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7733, 773, 'Operadores de usinagem convencional de madeira');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7734, 773, 'Operadores de máquina de usinar madeira (produção em série)');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7735, 773, 'Operadores de máquinas de usinagem de madeira cnc');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7741, 774, 'Montadores de móveis e artefatos de madeira');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7751, 775, 'Trabalhadores de arte e do acabamento em madeira do mobiliário');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7764, 776, 'Confeccionadores de artefatos de madeira, móveis de vime e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7771, 777, 'Carpinteiros navais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7772, 777, 'Carpinteiros de carrocerias e carretas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7801, 780, 'Supervisores de trabalhadores de embalagem e etiquetagem');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7811, 781, 'Condutores de processos robotizados');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7813, 781, 'Operadores de equipamentos pilotados remotamente');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7817, 781, 'Trabalhadores subaquáticos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7821, 782, 'Operadores de máquinas e equipamentos de elevação');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7822, 782, 'Operadores de equipamentos de movimentação de cargas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7823, 782, 'Motoristas de veículos de pequeno e médio porte');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7824, 782, 'Motoristas de ônibus urbanos, metropolitanos e rodoviários');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7825, 782, 'Motoristas de veículos de cargas em geral');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7826, 782, 'Operadores de veículos sobre trilhos e cabos aéreos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7827, 782, 'Trabalhadores aquaviários');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7828, 782, 'Condutores de animais e de veículos de tração animal e pedais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7831, 783, 'Trabalhadores de manobras de transportes sobre trilhos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7832, 783, 'Trabalhadores de cargas e descargas de mercadorias');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7841, 784, 'Trabalhadores de embalagem e de etiquetagem');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7842, 784, 'Alimentadores de linhas de produção');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (7911, 791, 'Artesãos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8101, 810, 'Supervisores de produção em indústrias químicas, petroquímicas e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8102, 810, 'Supervisores de produção em indústrias de transformação de plásticos e borrachas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8103, 810, 'Supervisores de produção em indústrias de produtos farmacêuticos, cosméticos e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8110, 811, 'Operadores polivalentes de equipamentos em indústrias químicas, petroquímicas e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8111, 811, 'Operadores de equipamentos de moagem e mistura de materiais (tratamentos químicos e afins)');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8112, 811, 'Operadores de calcinação e de tratamentos químicos de materiais radioativos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8113, 811, 'Operadores de equipamentos de filtragem e separação');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8114, 811, 'Operadores de equipamentos de destilação, evaporação e reação');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8115, 811, 'Operadores de equipamentos de produção e refino de petróleo e gás');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8116, 811, 'Operadores de equipamentos de coqueificação');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8117, 811, 'Operadores de instalações e máquinas de produtos plásticos, de borracha e moldadores de parafinas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8118, 811, 'Operadores de máquinas e instalações de produtos farmacêuticos, cosméticos e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8121, 812, 'Trabalhadores da fabricação de munição e explosivos químicos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8131, 813, 'Operadores de processos das indústrias de transformação de produtos químicos, petroquímicos e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8181, 818, 'Laboratoristas industriais auxiliares');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8201, 820, 'Supervisores de produção em indústrias siderúrgicas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8202, 820, 'Supervisores na fabricação de materiais para construção (vidros e cerâmicas)');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8211, 821, 'Operadores de instalações de sinterização');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8212, 821, 'Operadores de fornos de primeira fusão e aciaria');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8213, 821, 'Operadores de equipamentos de laminação');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8214, 821, 'Operadores de equipamentos de acabamento de chapas e metais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8221, 822, 'Forneiros metalúrgicos (segunda fusão e reaquecimento)');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8231, 823, 'Operadores na preparação de massas para abrasivo, vidro, cerâmica, porcelana e materiais de construção');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8232, 823, 'Operadores de equipamentos de fabricação e beneficiamento de cristais, vidros, cerâmicas, porcelanas, fibras de vidro, abrasivos e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8233, 823, 'Operadores de instalações e equipamentos de fabricação de materiais de construção');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8281, 828, 'Trabalhadores da fabricação de cerâmica estrutural para construção');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8301, 830, 'Supervisores da fabricação de celulose e papel');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8311, 831, 'Preparadores de pasta para fabricação de papel');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8321, 832, 'Operadores de máquinas de fabricar papel e papelão');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8331, 833, 'Operadores de máquinas na fabricação de produtos de papel e papelão');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8332, 833, 'Trabalhadores artesanais de produtos de papel e papelão');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8401, 840, 'Supervisores da fabricação de alimentos, bebidas e fumo');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8411, 841, 'Trabalhadores da indústria de beneficiamento de grãos, cereais e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8412, 841, 'Trabalhadores no beneficiamento do sal');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8413, 841, 'Trabalhadores na fabricação e refino de açúcar');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8414, 841, 'Trabalhadores na fabricação e conservação de alimentos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8415, 841, 'Trabalhadores na pasteurização do leite e na fabricação de laticínios e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8416, 841, 'Trabalhadores na industrialização de café, cacau, mate e de produtos afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8417, 841, 'Trabalhadores na fabricação de cachaça, cerveja, vinhos e outras bebidas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8418, 841, 'Operadores de equipamentos na fabricação de pães, massas alimentícias, doces, chocolates e achocolatados');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8421, 842, 'Cigarreiros e beneficiadores de fumo');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8422, 842, 'Charuteiros');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8423, 842, 'Cigarreiros');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8481, 848, 'Trabalhadores artesanais na conservação de alimentos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8482, 848, 'Trabalhadores artesanais na pasteurização do leite e na fabricação de laticínios e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8483, 848, 'Padeiros, confeiteiros e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8484, 848, 'Trabalhadores na degustação e classificação de grãos e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8485, 848, 'Magarefes e afins');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8486, 848, 'Trabalhadores artesanais na indústria do fumo');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8601, 860, 'Supervisores da produção de utilidades');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8611, 861, 'Operadores de instalações de geração e distribuição de energia elétrica, hidráulica, térmica ou nuclear');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8612, 861, 'Operadores de instalações de distribuição de energia elétrica');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8621, 862, 'Operadores de máquinas a vapor e utilidades');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8622, 862, 'Operadores de instalações de captação, tratamento e distribuição de água');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8623, 862, 'Operadores de instalações de captação e esgotos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8624, 862, 'Operadores de instalações de extração, processamento, envasamento e distribuição de gases');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (8625, 862, 'Operadores de instalações de refrigeração e ar-condicionado');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9101, 910, 'Supervisores em serviços de reparação e manutenção de máquinas e equipamentos industriais, comerciais e residenciais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9102, 910, 'Supervisores em serviços de reparação e manutenção veicular');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9109, 910, 'Supervisores de outros trabalhadores de serviços de reparação, conservação e manutenção');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9111, 911, 'Mecânicos de manutenção de bombas, motores, compressores e equipamentos de transmissão');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9112, 911, 'Mecânicos de manutenção e instalação de aparelhos de climatização e refrigeração');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9113, 911, 'Mecânicos de manutenção de máquinas industriais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9131, 913, 'Mecânicos de manutenção de máquinas pesadas e equipamentos agrícolas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9141, 914, 'Mecânicos de manutenção aeronáutica');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9142, 914, 'Mecânicos de manutenção de motores e equipamentos navais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9143, 914, 'Mecânicos de manutenção metroferroviária');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9144, 914, 'Mecânicos de manutenção de veículos automotores');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9151, 915, 'Técnicos em manutenção e reparação de instrumentos de medição e precisão');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9152, 915, 'Restauradores de instrumentos musicais');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9153, 915, 'Técnicos em manutenção e reparação de equipamentos biomédicos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9154, 915, 'Reparadores de equipamentos fotográficos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9191, 919, 'Lubrificadores');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9192, 919, 'Trabalhadores de manutenção de roçadeiras, motoserras e similares');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9193, 919, 'Mecânicos de manutenção de bicicletas e equipamentos esportivos e de ginástica');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9501, 950, 'Supervisores de manutenção eletroeletrônica industrial, comercial e predial');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9502, 950, 'Supervisores de manutenção eletroeletrônica veicular');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9503, 950, 'Supervisores de manutenção eletromecânica');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9511, 951, 'Eletricistas de manutenção eletroeletrônica');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9513, 951, 'Instaladores e mantenedores de sistemas eletroeletrônicos de segurança');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9531, 953, 'Eletricistas eletrônicos de manutenção veicular (aérea, terrestre e naval)');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9541, 954, 'Instaladores e mantenedores eletromecânicos de elevadores, escadas e portas automáticas');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9542, 954, 'Reparadores de aparelhos eletrodomésticos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9543, 954, 'Reparadores de equipamentos de escritório');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9911, 991, 'Conservadores de vias permanentes (trilhos)');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9912, 991, 'Mantenedores de equipamentos de parques de diversões e similares');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9913, 991, 'Reparadores de carrocerias de veículos');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9914, 991, 'Mantenedores de edificações');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9921, 992, 'Trabalhadores elementares de serviços de manutenção veicular');
insert into Cbo2002.Familia (Codigo, SubGrupoCodigo, Titulo) values (9922, 992, 'Trabalhadores operacionais de conservação de vias permanentes (exceto trilhos)');
